// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoc5uCrNfqHikzE6TEsN9ZscFbYC5lrI',
    appId: '1:1023135037344:web:fb59f4291f989f34a316c5',
    messagingSenderId: '1023135037344',
    projectId: 'budget-tracker-3d250',
    authDomain: 'budget-tracker-3d250.firebaseapp.com',
    storageBucket: 'budget-tracker-3d250.firebasestorage.app',
    measurementId: 'G-2BJ3DFLFLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4xF2cYuTXHwTQDBV1fWIjKYdwhhEuAsA',
    appId: '1:1023135037344:android:b7cd34af70000c79a316c5',
    messagingSenderId: '1023135037344',
    projectId: 'budget-tracker-3d250',
    storageBucket: 'budget-tracker-3d250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzTEyC17u-wfiVhAV60rHnfpICEClznsY',
    appId: '1:1023135037344:ios:b23381a427b6d541a316c5',
    messagingSenderId: '1023135037344',
    projectId: 'budget-tracker-3d250',
    storageBucket: 'budget-tracker-3d250.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzTEyC17u-wfiVhAV60rHnfpICEClznsY',
    appId: '1:1023135037344:ios:b23381a427b6d541a316c5',
    messagingSenderId: '1023135037344',
    projectId: 'budget-tracker-3d250',
    storageBucket: 'budget-tracker-3d250.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmoc5uCrNfqHikzE6TEsN9ZscFbYC5lrI',
    appId: '1:1023135037344:web:8181f5b24957ab3ba316c5',
    messagingSenderId: '1023135037344',
    projectId: 'budget-tracker-3d250',
    authDomain: 'budget-tracker-3d250.firebaseapp.com',
    storageBucket: 'budget-tracker-3d250.firebasestorage.app',
    measurementId: 'G-384T7S0SWY',
  );

}